### ISSUE TITLE
implement matrial-ui elements

### ISSUE THREAD

**Issue by samuelwondimu** [moveyourdigital/editorjs-blocks-react-renderer#40]
### Purpose
- [x ] New renderer

### Description
most react users use material-ui for styling and i have done a editorjs blog project which rendres the json in to matrial-ui components

### Possible solution
`    
     case "image":
        return (
          <Box sx={{ py: 2 }}>
            <img
              src={block.data.file.url}
              style={{ width: "100%", borderRadius: 5 }}
              alt={block.data.file.url}
            />
            <Typography
              variant='body1'
              color='GrayText'
              dangerouslySetInnerHTML={{ __html: `| ${block.data.caption}` }}
              sx={{ pt: 1 }}
            />
          </Box>
        );

      case "table":
        return (
          <Table>
            <TableHead>
              {block.data.header.map((header: any) => (
                <TableCell key={header}>{header}</TableCell>
              ))}
            </TableHead>
            <TableBody>
              {block.data.rows.map((row: any) => (
                <TableRow key={row}>
                  {row.map((cell: any) => (
                    <TableCell>{cell}</TableCell>
                  ))}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        );
      case "paragraph":
        return (
          <Box
            component={Typography}
            paragraph
            sx={{
              fontSize: "20px",
              fontWeight: "400",
              letterSpacing: "0.5px",
            }}
            dangerouslySetInnerHTML={{ __html: `${block.data.text}` }}
          />
        );

      case "delimiter":
        return (
          <Box
            py={2}
            sx={{
              lineHeight: "1.6rem",
              width: "100%",
              textAlign: "center",
              "&::before": {
                content: '"*****"',
                display: "inline-block",
                width: "100%",
                height: "1.6rem",
                lineHeight: "1.6rem",
                fontSize: "2.6rem",
                fontWeight: "bold",
                letterSpacing: "0.2rem",
              },
            }}
          />
        );
      case "qoute":
        return (
          <Box p={2} my={2} sx={{ backgroundColor: "#E5FFEA" }}>
            <Stack direction='row' alignItems='center' spacing={2}>
              <Typography fontSize={"4rem"}>“</Typography>
              <Typography
                sx={{
                  fontSize: "1.3rem",
                  fontWeight: "bold",
                  fontStyle: "italic",
                }}
                color='text.secondary'
                dangerouslySetInnerHTML={{ __html: `${block.data.text}` }}
              />
              <Typography fontSize={"4rem"}>“</Typography>
            </Stack>
            <Typography
              variant='body1'
              color='GrayText'
              textAlign='right'
              dangerouslySetInnerHTML={{ __html: `${block.data.caption}` }}
              sx={{ pt: 1 }}
            />
          </Box>
        );

      case "embed":
        return (
          <Box
            sx={{
              position: "relative",
              width: "100%",
              overflow: "hidden",
              pt: "56.2%",
            }}
          >
            <iframe
              title='youtube'
              style={{
                position: "absolute",
                top: "0",
                left: "0",
                bottom: "0",
                right: "0",
                width: "100%",
                height: "100%",
                border: "none",
              }}
              frameBorder='0'
              src={block.data.embed}
              allow='autoplay; encrypted-media'
            />
          </Box>
        );

      case "list":
        let count = 1;
        return (
          <Box>
            <List>
              {block.data.style === "unordered"
                ? block.data.items.map((item: string) => {
                    return (
                      <>
                        <ListItem>
                          <Stack direction='row' spacing={1} alignItems='center'>
                            <Box
                              sx={{
                                height: "10px",
                                width: "10px",
                                backgroundColor: "#000000",
                                borderRadius: "50%",
                                display: "inline-block",
                              }}
                            />
                            <Typography
                              variant='body1'
                              color='black'
                              gutterBottom
                              dangerouslySetInnerHTML={{ __html: `${item}` }}
                              sx={{
                                fontSize: "18px",
                                fontWeight: "400",
                                letterSpacing: "0.5px",
                              }}
                            />
                          </Stack>
                        </ListItem>
                      </>
                    );
                  })
                : block.data.items.map((item: string) => {
                    return (
                      <ListItem>
                        <Stack direction='row' spacing={2}>
                          <Typography variant='body1' fontWeight='bold'>
                            {count++}
                          </Typography>
                          <Typography
                            variant='body1'
                            color='black'
                            gutterBottom
                            dangerouslySetInnerHTML={{ __html: `${item}` }}
                            sx={{
                              fontSize: "18px",
                              fontWeight: "400",
                              letterSpacing: "0.5px",
                            }}
                          />
                        </Stack>
                      </ListItem>
                    );
                  })}
            </List>
          </Box>
        );

      default:
        console.log("Unknown block type", block.type);
    }
    return null;
  });
}
`

**Comment by lightningspirit** [comment]
Hi @samuelwondimu 👋 thanks for your contribution.
This library is flexible enough to do what you want, just passing an object of custom render components to the `renderers` prop of `Blocks` you can achieve what you want.

Example, using your idea:
```ts
const ImageComponent: RenderFn<{
  items: string[]
}> = ({
  data, className = ""
}) => {
  return (
    <>
      <Box sx={{ py: 2 }}>
        <img src={data.file.url} style={{ width: "100%", borderRadius: 5 }} alt={block.data.file.url} />
        <Typography variant='body1' color='GrayText' dangerouslySetInnerHTML={{ __html:| ${data.caption}` }} sx={{ pt: 1 }} />
    </>
  )
}

export default () => <Blocks data={dataFromEditor} renderers={{
  image: ImageComponent
}} />
```

I want to keep this library flexible, lightweight and by default to render directly some plain HTML tags, hence I don't think we should lock or include specific frameworks here.

A possible solution for this problem is to create a simple wrapper, in an external library, that implements Material UI components and passes them directly to the `Blocks`.

**Comment by samuelwondimu** [comment]
you're right if we can create custom components and render them in the renderers that makes suitable for any type of framework we can use good to know
